#!/bin/bash
# TabBar 图标下载脚本
# 注意：此脚本需要手动执行，因为需要从网站下载

echo "=== TabBar 图标下载指南 ==="
echo ""
echo "由于无法自动下载，请按以下步骤操作："
echo ""
echo "1. 访问 IconFont: https://www.iconfont.cn/"
echo "2. 注册/登录账号"
echo "3. 搜索并下载以下图标："
echo ""
echo "   首页图标："
echo "   - 搜索 'home' 或 '首页'"
echo "   - 选择实心房子图标（选中状态）"
echo "   - 选择轮廓房子图标（未选中状态）"
echo "   - 下载 PNG 格式，81px"
echo ""
echo "   课程表图标："
echo "   - 搜索 'calendar' 或 'schedule'"
echo "   - 选择带勾选的日历图标"
echo "   - 下载 PNG 格式，81px"
echo ""
echo "   排行榜图标："
echo "   - 搜索 'trophy' 或 '奖杯'"
echo "   - 选择奖杯图标"
echo "   - 下载 PNG 格式，81px"
echo ""
echo "   我的图标："
echo "   - 搜索 'user' 或 '用户'"
echo "   - 选择人物图标"
echo "   - 下载 PNG 格式，81px"
echo ""
echo "4. 使用图片编辑工具调整颜色："
echo "   - 未选中：改为 #999999（灰色）"
echo "   - 选中：改为 #1a1a1a（深色）"
echo ""
echo "5. 重命名文件并放入 images/ 目录："
echo "   home.png / home-active.png"
echo "   schedule.png / schedule-active.png"
echo "   ranking.png / ranking-active.png"
echo "   profile.png / profile-active.png"
echo ""
